/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.szwajkowski;

import com.google.common.collect.Lists;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) throws IOException {
        List<Integer> collect = Files.readAllLines(Paths.get("input.txt")).stream().map(Integer::parseInt)
                .collect(Collectors.toList());

        System.out.println(collect.stream().mapToInt(i -> i).sum());

        List<Integer> values = Lists.newArrayList(0);
        System.out.println(find(collect, values, 0));
    }

    private static int find(List<Integer> collect, List<Integer> values, int acc) {
        for (int i : collect) {
            acc += i;
            if (values.contains(acc)) {
                return acc;
            }
            values.add(acc);
        }
        return find(collect, values, acc);
    }
}
